version: "3"

services:
  db:
    image: postgres:14.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: rad_user
      POSTGRES_PASSWORD: rad_p4ss
      POSTGRES_DB: rad
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
